import smtplib, ssl

sender_email = "stockmonitoradelaide@gmail.com"
receiver_email = "jamespang14@gmail.com"
andrew_email = "andrew@availer.com"
password = "Cal060996633"
smtp_server = 'smtp.gmail.com'


message = f'''\
Subject: Stockmon automated email test

This following message is generated by StockMonitor.
https://stockmonita.herokuapp.com
'''

server = smtplib.SMTP('smtp.gmail.com:587')
server.ehlo()
server.starttls()
server.ehlo()
server.login(sender_email,password)
server.sendmail(sender_email,receiver_email,message)
server.sendmail(sender_email,andrew_email,message)

server.quit()